apiVersion : apps/v1
kind : Deployment
metadata:
  name: sample-django
  labels:
    project: sample-django
    owner : Voloshin_Nikolai
spec:
  selector:
    matchLabels:
      project: sample-django
  template:
    metadata:
      labels:
        name: sample-django
        project: sample-django
    spec:
      containers:
        - name : sample-django
          image: gcr.io/kubernetes-329812/sample-django:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-url
                key: db_url
